### ISSUE TITLE
Ramen recipe

### ISSUE THREAD

**Issue by LEWeee** [Lgmrszd/TFC-TNG_BWM_GT-CE#1]
I created this issue for 2 reasons:
1.) It's one of the first issues we got regarding this modpack
2.) I though it would be funny if the first issue was about this

The problem is that the recipe for Ramen Dough in Sakura requires the use of Alkali.
![image](https://user-images.githubusercontent.com/16687385/101986246-34462680-3c8d-11eb-926c-9db13d0693ee.png)

In Sakura, Alkali is by default made in the Stone Mortar out of Stone, though this in bit of a dispute with TFC's design philosophy. While it's not exactly known why is Alkali made this way I assume it's that way to be consistent with Sakura's table Salt recipe (Alkali recipe - top, Salt recipe - bottom)
![image](https://user-images.githubusercontent.com/16687385/101986448-2ba22000-3c8e-11eb-9948-8b8cd093c75c.png)
![image](https://user-images.githubusercontent.com/16687385/101986451-3066d400-3c8e-11eb-974f-55c8230ed80f.png)

While the first idea was to simply replace Alkali with Salt this was very quickly discarded because Alkali and Salt are separate items in Sakura and also the fact [Alkali seems to be an important part of making Ramen dough](https://en.wikipedia.org/wiki/Alkaline_pasta)

This issue seeks to discuss a different crafting recipe for Alkali

**Comment by Lgmrszd** [comment]
[This article](https://en.wikipedia.org/wiki/Sodium_carbonate#Production) states that Sodium carbonate is either obtained from trona (mining) or by processing seaweed.
